title: Marc Weistroff
tagline: 
email: marc@weistroff.net
description: > # this means to ignore newlines until "baseurl:"
    Hi and welcome to my personnal website!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 10
permalink: pretty

author:
    name: Marc Weistroff
    url: http://marc.weistroff.net
    email: marc@weistroff.net

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: 'jekyll-theme-lanyon'
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor

